import {calculate} from './screener.mjs';
const headers={'User-Agent':'Mozilla/5.0','Accept':'application/json','Origin':'https://www.nasdaq.com'};
async function json(url,signal){let last;for(let i=0;i<3;i++){try{const r=await fetch(url,{headers,signal:signal?AbortSignal.any([signal,AbortSignal.timeout(25000)]):AbortSignal.timeout(25000)});if(!r.ok)throw Error('Market source returned HTTP '+r.status);return await r.json()}catch(e){if(signal?.aborted)throw e;last=e;await new Promise(r=>setTimeout(r,500*(i+1)))}}throw last;}
export async function publicUniverse({all=false,signal}={}){
 const listings=await Promise.all(['NASDAQ','NYSE'].map(async exchange=>{
  const j=await json('https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=10000&exchange='+exchange.toLowerCase(),signal),d=j.data,rows=d?.table?.rows;
  if(!Array.isArray(rows)||rows.length<Number(d.totalrecords))throw Error(exchange+' universe unavailable or incomplete');
  return rows.map(s=>({...s,companyName:s.name,marketCap:Number(String(s.marketCap).replaceAll(',','')),exchangeShortName:exchange,_source:'nasdaq-yahoo',marketCapAsOf:d.asof}));
 }));
 return [...new Map(listings.flat().filter(s=>(all||s.marketCap>=20e9&&s.marketCap<=100e9)&& !/\b(warrant|rights|preferred|depositary shares|notes due|ETF|exchange.traded fund)\b/i.test(s.name)).map(s=>[s.symbol,s])).values()];
}
export async function publicStock(s,w,{signal}={}){const ticker=s.symbol.replace(/\./g,'-'),u=new URL('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(ticker));u.searchParams.set('period1',String(Date.parse(w.baseline+'T00:00:00Z')/1000));u.searchParams.set('period2',String(Date.parse(w.end+'T00:00:00Z')/1000+86400));u.searchParams.set('interval','1d');u.searchParams.set('events','splits');const j=await json(u,signal),r=j.chart?.result?.[0];if(!r||j.chart.error)throw Error('Historical prices unavailable');if(r.meta.instrumentType!=='EQUITY'||!['NMS','NGM','NCM','NAS','NYQ','NYSE'].includes(r.meta.exchangeName))throw Error('Not a NASDAQ or NYSE equity');const q=r.indicators?.quote?.[0]?.close;if(!Array.isArray(r.timestamp)||!Array.isArray(q))throw Error('Missing history');const now=new Date(),parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now).map(x=>[x.type,x.value]));const closed=Number(parts.hour)*60+Number(parts.minute)>=16*60+15;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);const history=r.timestamp.map((t,i)=>({date:new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(t*1000)),close:q[i],low:r.indicators.quote[0].low?.[i],high:r.indicators.quote[0].high?.[i]})).filter(p=>p.close>0&&(p.date!==today||closed));const result=calculate(s,history,w);return {...result,source:'NASDAQ screener / Yahoo Finance',marketCapAsOf:s.marketCapAsOf,price:r.meta.regularMarketPrice>0?r.meta.regularMarketPrice:result.price,priceAsOf:r.meta.regularMarketTime?new Date(r.meta.regularMarketTime*1000).toISOString():result.priceDate,priceKind:r.meta.regularMarketPrice>0?'Latest quote':'Latest close'};}
