import {normalizeFilters,capMatches,movementMatches} from './filters.mjs';
import {publicUniverse,publicStock} from './public-market.mjs';
export function dates(now=new Date(),lookbackDays=30){const end=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(now),start=new Date(end+'T00:00:00Z');start.setUTCDate(start.getUTCDate()-(lookbackDays-1));const baseline=new Date(start);baseline.setUTCDate(baseline.getUTCDate()-10-Math.max(0,30-lookbackDays));return {start:start.toISOString().slice(0,10),end,baseline:baseline.toISOString().slice(0,10)};}
export function calculate(stock,history,w){const p=[...history].sort((a,b)=>a.date.localeCompare(b.date)),days=[];if(new Set(p.map(x=>x.date)).size!==p.length)throw Error('Duplicate dates');for(let i=1;i<p.length;i++){if(p[i].date<w.start||p[i].date>w.end)continue;if(!(p[i].close>0&&p[i-1].close>0))throw Error('Invalid price');days.push({date:p[i].date,close:p[i].close,change:(p[i].close/p[i-1].close-1)*100});}if(!days.length||!p.some(x=>x.date<w.start))throw Error('Insufficient history');const rangeStart=new Date(w.end+'T00:00:00Z');rangeStart.setUTCDate(rangeStart.getUTCDate()-29);const range=p.filter(d=>d.date>=rangeStart.toISOString().slice(0,10)&&d.date<=w.end);const lows=range.map(d=>d.low).filter(v=>Number.isFinite(v)&&v>0),highs=range.map(d=>d.high).filter(v=>Number.isFinite(v)&&v>0);return {exchange:stock.exchangeShortName||stock.exchange,low30:lows.length===range.length?Math.min(...lows):null,high30:highs.length===range.length?Math.max(...highs):null,priceAsOf:days.at(-1).date,priceKind:'Latest close',symbol:stock.symbol,name:stock.companyName,marketCap:stock.marketCap,sector:stock.sector||'Other',average:days.reduce((s,d)=>s+Math.abs(d.change),0)/days.length,signedAverage:days.reduce((s,d)=>s+d.change,0)/days.length,change:days.at(-1).change,price:days.at(-1).close,priceDate:days.at(-1).date,largeDays:days.filter(d=>Math.abs(d.change)>=5).length,days};}
export async function provider(path,params,key){const u=new URL('https://financialmodelingprep.com/stable/'+path);Object.entries({...params,apikey:key}).forEach(([k,v])=>u.searchParams.set(k,String(v)));const r=await fetch(u,{signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('Provider HTTP '+r.status+'; check key, plan and rate limits');const j=await r.json();if(!Array.isArray(j))throw Error('Provider access unavailable');return j;}
export async function universe(key){
 if(key){try{const s=(await Promise.all(['NASDAQ','NYSE'].map(exchange=>provider('company-screener',{marketCapMoreThan:19999999999,marketCapLowerThan:100000000001,exchange,isEtf:false,isFund:false,isActivelyTrading:true,limit:10000},key).then(rows=>{if(rows.length>=10000)throw Error(exchange+' universe truncated');return rows.map(s=>({...s,exchangeShortName:exchange}))})))).flat();return s.filter(s=>s.marketCap>=20e9&&s.marketCap<=100e9&&/NASDAQ|NYSE/.test(String(s.exchangeShortName||s.exchange).toUpperCase())&&!s.isEtf&&!s.isFund).map(s=>({...s,_source:'fmp'}));}catch{}}
 return publicUniverse();
}
export async function scanStock(s,w,key,{signal}={}){if(s._source==='nasdaq-yahoo'||!key)return publicStock(s,w,{signal});try{return {...calculate(s,await provider('historical-price-eod/full',{symbol:s.symbol,from:w.baseline,to:w.end},key),w),source:'Financial Modeling Prep'};}catch{return publicStock(s,w,{signal});}}
export function makeReport(results,errors,w,total,options){const filters=normalizeFilters(options);const eligible=results.filter(s=>capMatches(s,filters)).sort((a,b)=>b.average-a.average||a.symbol.localeCompare(b.symbol));const matches=eligible.filter(s=>movementMatches(s,filters));return {exchanges:['NASDAQ','NYSE'],id:crypto.randomUUID(),createdAt:new Date().toISOString(),...w,filters,total,scanned:results.length,errors,complete:errors.length===0,sources:[...new Set(results.map(s=>s.source).filter(Boolean))],marketCapAsOf:results[0]?.marketCapAsOf||null,qualifying:matches.length,eligibleCount:eligible.length,top25:matches.slice(0,25).map(s=>({...s,meetsCriteria:true})),allMatches:matches.map(({days,...s})=>({...s,sessions:days?.length})),stocks:matches.slice(0,25)};}
