import {normalizeFilters,capMatches,describeFilters} from '../lib/filters.mjs';
import http from 'node:http';
import {nextScanTime,scanDue} from '../lib/scan-status.mjs';
import {csv,summaryRows} from '../lib/csv-report.mjs';
import {readFile,writeFile,mkdir,rename,open,unlink} from 'node:fs/promises';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {publicUniverse} from '../lib/public-market.mjs';
import {scanStock,dates,makeReport} from '../lib/screener.mjs';
import {reviewBatch,companyNews} from '../lib/research.mjs';
const root=dirname(dirname(fileURLToPath(import.meta.url))),out=join(root,'outputs');await mkdir(out,{recursive:true});
const statusPath=join(out,'agent-status.json'),reportPath=join(out,'report.json'),scanPath=join(out,'scan-checkpoint.json');
try{const pid=Number(await readFile(join(out,'agent.lock'),'utf8'));try{process.kill(pid,0)}catch{await unlink(join(out,'agent.lock'))}}catch{}
let runAbort,restartRequested=false;
let status={state:'idle',phase:'Ready',schedule:'Every 3 hours and whenever Run fresh scan is clicked',timezone:'America/Los_Angeles',discovered:0,reviewed:0,pricesScanned:0,aiReviewed:0},active=false;
try{status={...status,...JSON.parse(await readFile(statusPath,'utf8'))};if(['running','paused','error'].includes(status.state)){status.state='paused';status.phase='Interrupted scan will resume'}}catch{}
status.filters=normalizeFilters(status.filters);
status.schedule='Every 3 hours and whenever Run fresh scan is clicked';status.nextScanAt ||= nextScanTime();
const writes=new Map();async function save(path,value){const content=JSON.stringify(value);const promise=(writes.get(path)||Promise.resolve()).catch(()=>{}).then(async()=>{const temp=path+'.tmp';await writeFile(temp,content);await rename(temp,path)});writes.set(path,promise);await promise}
async function update(fields){status={...status,...fields,updatedAt:new Date().toISOString()};await save(statusPath,status)}
function day(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
async function publish(report){await save(reportPath,report);await writeFile(join(out,'top-25.csv'),csv(summaryRows(report.top25||[],report)));await writeFile(join(out,'all-matching-stocks.csv'),csv(summaryRows(report.allMatches||[],report)));try{const checkpoint=JSON.parse(await readFile(scanPath,'utf8'));await writeFile(join(out,'all-screened-stocks.csv'),csv(summaryRows(checkpoint.results,report)))}catch{}try{const origin=process.env.SITE_URL||'http://127.0.0.1:5173';const r=await fetch(new URL('/api/reports',origin),{method:'POST',headers:{'Content-Type':'application/json',Origin:new URL(origin).origin},body:JSON.stringify(report),signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Dashboard HTTP '+r.status);await update({upload:'saved'})}catch(e){await update({upload:'Report saved locally; dashboard upload pending'})}}
async function run({scheduled=false,fresh=false,filters=status.filters}={}){if(active)return;active=true;runAbort=new AbortController();const signal=runAbort.signal;const scanFilters=normalizeFilters(filters);let runReport;let lock;try{lock=await open(join(out,'agent.lock'),'wx');await lock.writeFile(String(process.pid))}catch{active=false;return}try{
 const resume=!fresh&&(status.state==='paused'||(!scheduled&&status.state==='error'));const w=dates(new Date(),scanFilters.lookbackDays),listing=await publicUniverse({all:true,signal});let results=[],errors=[],batches=[],researchErrors=[],completed=new Set();try{const saved=JSON.parse(await readFile(scanPath,'utf8'));if(resume&&saved.end===w.end&&saved.start===w.start&&JSON.stringify(saved.filters)===JSON.stringify(scanFilters)){results=saved.results||[];errors=saved.errors||[];batches=saved.batches||[];researchErrors=saved.researchErrors||[];completed=new Set([...results,...errors].map(r=>r.symbol))}}catch{}
 const eligible=listing.filter(s=>capMatches(s,scanFilters));
 await update({filters:scanFilters,state:'running',wasScheduled:scheduled,phase:'Scanning every NASDAQ company',startedAt:resume?status.startedAt:new Date().toISOString(),scanDate:w.end,discovered:listing.length,reviewed:listing.length,capEligible:eligible.length,pricesScanned:results.length+errors.length,aiReviewed:batches.reduce((s,b)=>s+b.symbolsCovered.length,0),priceErrors:errors.length,researchErrors:researchErrors.length,scanCompletedAt:null,completedAt:null});
 async function checkpoint(){await save(scanPath,{end:w.end,start:w.start,filters:scanFilters,results,errors,batches,researchErrors})}
 const pending=listing.filter(s=>!completed.has(s.symbol));let next=0;
 async function worker(){while(next<pending.length){const stock=pending[next++];try{results.push(await scanStock(stock,w,process.env.FMP_API_KEY,{signal}))}catch(e){if(signal.aborted)throw e;errors.push({symbol:stock.symbol,name:stock.companyName,marketCap:stock.marketCap,error:e.message})}await update({pricesScanned:results.length+errors.length,priceErrors:errors.length,currentSymbol:stock.symbol});if((results.length+errors.length)%25===0)await checkpoint();await new Promise(r=>setTimeout(r,500))}}
 await Promise.all([worker(),worker(),worker()]);await checkpoint();
 const report=makeReport(results,errors,w,listing.length,scanFilters);runReport=report;report.coverage={discovered:listing.length,reviewed:listing.length,capEligible:eligible.length,pricesScanned:results.length,priceErrors:errors.length,policy:'All NASDAQ companies scanned; report filters: '+describeFilters(scanFilters)};report.research={state:'running',model:process.env.OLLAMA_MODEL||'qwen3:0.6b',reviewed:status.aiReviewed,total:listing.length,batches:[],errors:researchErrors};await publish(report);
 await update({phase:'LLM reviewing every company',scanCompletedAt:new Date().toISOString(),currentSymbol:null});const already=new Set(batches.flatMap(b=>b.symbolsCovered));const data=[...results,...errors].filter(r=>!already.has(r.symbol));
 for(let i=0;i<data.length;i+=6){const rows=data.slice(i,i+6);for(const row of rows){try{row.headlines=await companyNews(row.symbol,{signal})}catch{if(signal.aborted)throw Error('Scan replaced by a fresh run');row.headlines=[]}}try{let b;try{b=await reviewBatch(rows,{model:process.env.OLLAMA_MODEL||'qwen3:0.6b',signal})}catch{if(signal.aborted)throw Error('Scan replaced by a fresh run');const singles=[];for(const row of rows)singles.push(await reviewBatch([row],{model:process.env.OLLAMA_MODEL||'qwen3:0.6b',signal}));b={model:process.env.OLLAMA_MODEL||'qwen3:0.6b',summary:`LLM reviewed ${rows.length} company records individually.`,observations:singles.flatMap(x=>x.observations),symbolsCovered:rows.map(r=>r.symbol),generatedAt:new Date().toISOString()}}batches.push(b)}catch(e){if(signal.aborted)throw e;researchErrors.push({symbols:rows.map(r=>r.symbol),error:e.message});if(researchErrors.length>=3&&batches.length===0)throw Error('Local LLM unavailable or unable to cover the first batches; numeric report preserved.')}await update({aiReviewed:batches.reduce((s,b)=>s+b.symbolsCovered.length,0),researchErrors:researchErrors.length,currentSymbol:rows.map(r=>r.symbol).join(', ')});await checkpoint();if(i%60===0){report.research={state:'running',model:process.env.OLLAMA_MODEL||'qwen3:0.6b',reviewed:status.aiReviewed,total:listing.length,batches:batches.slice(0,3),errors:researchErrors.slice(0,10)};await publish(report)}}
 report.research={state:researchErrors.length?'partial':'complete',model:process.env.OLLAMA_MODEL||'qwen3:0.6b',reviewed:status.aiReviewed,total:listing.length,batches:batches.slice(0,3),errors:researchErrors.slice(0,10),completedAt:new Date().toISOString()};const notes=new Map(batches.flatMap(b=>b.observations).map(o=>[o.symbol,o.note]));report.top25=(report.top25||[]).map(s=>({...s,aiNote:notes.get(s.symbol)||null,headlines:s.headlines||[]}));report.allMatches=(report.allMatches||[]).map(s=>({...s,aiNote:notes.get(s.symbol)||null}));report.stocks=report.stocks.map(s=>({...s,aiNote:notes.get(s.symbol)||null,headlines:s.headlines||[]}));await save(join(out,'research.json'),batches);await publish(report);await update({state:errors.length||researchErrors.length?'partial':'complete',phase:'Scan complete — results below',completedAt:new Date().toISOString(),lastRunDay:day(),lastScheduledDay:scheduled?day():status.lastScheduledDay,currentSymbol:null});
 }catch(e){if(signal.aborted){await update({state:'paused',phase:'Starting a fresh scan…'})}else{if(runReport){runReport.research={...runReport.research,state:'error',reviewed:status.aiReviewed,error:e.message};await publish(runReport)}await update({state:'error',phase:e.message,lastRunDay:day(),lastScheduledDay:scheduled?day():status.lastScheduledDay});console.error(e.message)}}finally{await lock.close();await unlink(join(out,'agent.lock')).catch(()=>{});active=false;if(restartRequested){restartRequested=false;void run({fresh:true})}}}
const token=process.env.LOCAL_AGENT_TOKEN;
const server=http.createServer(async(req,res)=>{res.setHeader('Content-Type','application/json');if(!token||req.headers.authorization!=='Bearer '+token){res.writeHead(401);return res.end(JSON.stringify({error:'Unauthorized'}))}const path=new URL(req.url,'http://127.0.0.1').pathname;if(path==='/status'){return res.end(JSON.stringify(status))}if(path.startsWith('/csv/')){const name=path.slice(5);if(!['top-25.csv','all-matching-stocks.csv','all-screened-stocks.csv'].includes(name)){res.writeHead(404);return res.end('{}')}try{res.setHeader('Content-Type','text/csv; charset=utf-8');return res.end(await readFile(join(out,name)))}catch{res.writeHead(404);return res.end('{}')}}if(path==='/report'){try{return res.end(await readFile(reportPath,'utf8'))}catch{res.writeHead(404);return res.end(JSON.stringify({error:'First report not ready'}))}}if(path==='/start'&&req.method==='POST'){let filters;try{let body='';for await(const chunk of req){body+=chunk;if(body.length>4096)throw Error('Request too large')}filters=normalizeFilters(body?JSON.parse(body).filters:status.filters)}catch(e){res.writeHead(400);return res.end(JSON.stringify({error:e.message}))}await update({filters});const replacing=active;if(active){restartRequested=true;runAbort?.abort()}else void run({fresh:true,filters});res.writeHead(202);return res.end(JSON.stringify({started:true,replacing,fresh:true,filters}))}res.writeHead(404);res.end('{}')});
server.listen(8766,'127.0.0.1',()=>console.log('Daily NASDAQ agent listening on 127.0.0.1:8766'));
async function schedule(){if(!scanDue(status.nextScanAt))return;await update({nextScanAt:nextScanTime()});if(active){restartRequested=true;runAbort?.abort()}else void run({scheduled:true,fresh:true})}
setInterval(()=>void schedule(),60000);void update({schedule:status.schedule,nextScanAt:status.nextScanAt});if(status.state==='paused'||!status.lastRunDay)void run({scheduled:Boolean(status.wasScheduled)});else void schedule();
