import test from 'node:test';import assert from 'node:assert/strict';import {calculate,dates,makeReport} from '../lib/screener.mjs';
const s={symbol:'TEST',companyName:'Test',marketCap:20e9},w={start:'2026-09-01',end:'2026-09-30'};
test('opposing moves do not cancel and pre-window close is used',()=>{const r=calculate(s,[{date:'2026-08-31',close:100},{date:'2026-09-01',close:110},{date:'2026-09-02',close:99}],w);assert.ok(Math.abs(r.average-10)<1e-9);assert.ok(Math.abs(r.signedAverage)<1e-9);assert.equal(r.largeDays,2)});
test('30 calendar days across month boundary',()=>assert.deepEqual(dates(new Date('2026-10-05T22:00:00Z')),{start:'2026-09-06',end:'2026-10-05',baseline:'2026-08-27'}));
test('missing baseline is rejected',()=>assert.throws(()=>calculate(s,[{date:'2026-09-01',close:100},{date:'2026-09-02',close:105}],w)));
test('rank and threshold return only top 25 and flag incomplete coverage',()=>{const a=Array.from({length:30},(_,i)=>({symbol:'T'+i,average:i,marketCap:20e9}));const r=makeReport(a,[{symbol:'FAIL'}],w,31);assert.equal(r.stocks.length,25);assert.equal(r.stocks[0].average,29);assert.equal(r.qualifying,25);assert.equal(r.complete,false);assert.equal(r.scanned,30)});

test('all-universe results retain the original inclusive market-cap limits',()=>{const r=makeReport([{symbol:'SMALL',average:20,marketCap:19e9},{symbol:'BIG',average:20,marketCap:101e9},{symbol:'LOW',average:6,marketCap:20e9},{symbol:'HIGH',average:7,marketCap:100e9}],[],w,4);assert.equal(r.scanned,4);assert.deepEqual(r.stocks.map(s=>s.symbol),['HIGH','LOW'])});

test('top25 contains matches only and full CSV list is not truncated',()=>{const r=makeReport(Array.from({length:30},(_,i)=>({symbol:'T'+i,average:4-i/100,marketCap:30e9,days:[]})),[],w,30);assert.equal(r.qualifying,0);assert.equal(r.top25.length,0);const q=makeReport(Array.from({length:30},(_,i)=>({symbol:'T'+i,average:6+i/100,marketCap:30e9,days:[]})),[],w,30);assert.equal(q.allMatches.length,30);assert.equal(q.top25.length,25)});
