import {normalizeFilters,matchesFilters} from './filters.mjs';
import {csv,summaryRows} from './csv-report.mjs';
const $=id=>document.getElementById(id);
let data,match=[],currentReport;
const money=v=>Number.isFinite(v)?'$'+v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
function renderNews(){const target=$('newsRows');target.replaceChildren();for(const s of match.slice(0,25)){const saved=data.report.newsStocks?.find(n=>n.symbol===s.symbol)||s;const row=document.createElement('tr'),stock=document.createElement('td'),news=document.createElement('td');stock.textContent=`${s.name} (${s.symbol})`;for(const h of saved.headlines||[]){if(!/^https:\/\//.test(h.url))continue;const a=document.createElement('a');a.href=h.url;a.target='_blank';a.rel='noreferrer';a.textContent=h.title;const item=document.createElement('p');item.append(a);news.append(item)}if(!news.children.length)news.textContent=saved.newsStatus||'No news in this snapshot for this company. Headlines refresh with the next scan.';row.append(stock,news);target.append(row)}if(!match.length){const row=document.createElement('tr'),cell=document.createElement('td');cell.colSpan=2;cell.textContent='News appears here for stocks matching your filters.';row.append(cell);target.append(row)}}
$('topCsv').onclick=()=>download(match.slice(0,25),'top-25.csv');$('allCsv').onclick=()=>download(match,'all-matching-stocks.csv');
function apply(){try{const f=normalizeFilters({minMarketCap:Number($('minCap').value)*1e9,maxMarketCap:Number($('maxCap').value)*1e9,minAverage:Number($('minMove').value),maxAverage:$('maxMove').value===''?null:Number($('maxMove').value),lookbackDays:Number($('days').value)});if(f.lookbackDays>data.report.filters.lookbackDays)throw Error(`This scan contains ${data.report.filters.lookbackDays} calendar days. Choose a lookback within the available history.`);const start=new Date(data.report.end+'T00:00:00Z');start.setUTCDate(start.getUTCDate()-(f.lookbackDays-1));const startDate=start.toISOString().slice(0,10);currentReport={...data.report,filters:f,start:startDate};match=data.stocks.map(s=>{const days=s.history.filter(d=>d[0]>=startDate);if(!days.length)return null;return {...s,average:days.reduce((n,d)=>n+Math.abs(d[2]),0)/days.length,signedAverage:days.reduce((n,d)=>n+d[2],0)/days.length,largeDays:days.filter(d=>Math.abs(d[2])>=5).length,sessions:days.length,change:days.at(-1)[2],priceDate:days.at(-1)[0]}}).filter(s=>s&&matchesFilters(s,f)).sort((a,b)=>b.average-a.average||a.symbol.localeCompare(b.symbol));$('rows').replaceChildren();match.slice(0,25).forEach((s,i)=>{const tr=document.createElement('tr');[i+1,`${s.name} (${s.symbol})`,`$${(s.marketCap/1e9).toFixed(2)}B`,`${s.change.toFixed(2)}%`,`${s.average.toFixed(2)}%`,money(s.price),money(s.low30),money(s.high30)].forEach((v,j)=>{const td=document.createElement('td');td.textContent=v;if(j===3)td.className=s.change>=0?'positive':'negative';tr.append(td)});$('rows').append(tr)});renderNews();$('count').textContent=`· ${match.length} matches`;$('empty').textContent=match.length?'':'No stocks match these conditions. Adjust the filters to explore the scanned universe.';$('status').textContent=`Scan complete — results below. ${data.report.scanned.toLocaleString()} / ${data.report.total.toLocaleString()} companies have valid histories; ${data.report.errors.length} failures. Completed ${new Date(data.report.createdAt).toLocaleString()}. Prices are the latest available scan quotes or closes, not streaming prices. Applying filters does not fetch new market data.`;$('details').textContent=`Window: ${startDate} to ${data.report.end} (${f.lookbackDays} calendar days). Source: ${data.report.sources.join(', ')}. Market cap as of ${data.report.marketCapAsOf||data.report.createdAt}. ${data.report.complete?'Complete price coverage.':'Partial price coverage; some stocks could not be evaluated.'}`;$('topCsv').disabled=false;$('allCsv').disabled=false}catch(e){$('status').textContent=e.message}}
$('filters').onsubmit=e=>{e.preventDefault();if(data)apply()};
try{const r=await fetch('data.json',{cache:'no-store'});if(!r.ok)throw Error('The first scan has not published yet. Check GitHub Actions for progress.');data=await r.json();const f=data.report.filters;$('minCap').value=f.minMarketCap/1e9;$('maxCap').value=f.maxMarketCap/1e9;$('minMove').value=0;$('maxMove').value=5;$('days').value=f.lookbackDays;apply()}catch(e){$('status').textContent=e.message}
